Repository Jiralite/RuneScape, pull requests merged in 2024-12, with the labels that each got.

#38 feat(QuestTitle): Add A Christmas Reunion
  source/rune-metrics.ts
Labels: Enhancement

#40 types(wilderness-warbands): Explicit boolean
  source/wilderness-warbands.ts
Labels: Enhancement

#41 ci: Add JSR
  .github/workflows/publish.yaml
  jsr.json
Labels: CI

#42 types: Allow an explicit `undefined`
  source/hi-scores.ts
  source/miscellaneous.ts
  source/rune-metrics.ts
  source/utility/make-request.ts
Labels: Types
