Repository Jiralite/RuneScape, pull requests merged in 2024-11, with the labels that each got.

#27 fix: Truncate runedates in calculations
  source/jewels.ts
  source/travelling-merchant.ts
Labels: Fix

#28 feat: Group Ironman HiScores
  source/hi-scores.ts
  source/index.ts
Labels: Enhancement

#29 feat(QuestTitle): Updated quests
  source/quest-details.ts
Labels: Enhancement

#30 docs(hi-scores): Document `groupIronman`
  source/hi-scores.ts
Labels: Documentation

#33 feat: Add created accounts
  source/index.ts
  source/miscellaneous.ts
Labels: Enhancement

#34 refactor(profile): Remove extra `/profile`
  source/profile.ts
Labels: Refactor

#35 refactor: Aggregate RuneMetrics endpoints
  source/index.ts
  source/profile.ts
  source/rune-metrics.ts
Labels: Refactor

#36 chore: Remove ESLint comments
  source/wilderness-flash-event.ts
Labels: Chore

#37 fix(travelling-merchant): Calculate stock from the date only
  source/travelling-merchant.ts
Labels: Fix
